language: python

python:
  - "3.6"

install:
  - pip install flake8 jupyterlab~=1.2

script:
  - flake8 .
  - python setup.py sdist
  - python -mpip install dist/*.tar.gz
  - jlpm
  - jupyter labextension install

deploy:
  - provider: pypi
    user: __token__
    # password: $PYPI_PASSWORD
    skip_existing: true
    on:
      tags: true
  # https://travis-ci.community/t/missing-api-key-when-deploying-to-github-releases/5761/14
  # https://docs.travis-ci.com/user/deployment-v2/providers/npm/
  - provider: npm
    edge: true
    email: $NPM_EMAIL
    # api_key: $NPM_API_TOKEN
    on:
      tags: true
