language: python
dist: bionic
python:
  - "3.6"

addons:
  firefox: latest

before_install:
  - mkdir $HOME/geckodriver
  - curl -sSfL https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz | tar -C $HOME/geckodriver -zx
  - export PATH=$PATH:$HOME/geckodriver

install:
  - pip install -r dev-requirements.txt

script:
  - pwd
  - flake8 .
  - python setup.py sdist
  - python -mpip install dist/*.tar.gz
  - jlpm
  - jupyter labextension install --debug
  - pytest -vs tests

deploy:
  - provider: pypi
    user: __token__
    # password: $PYPI_PASSWORD
    skip_existing: true
    on:
      tags: true
  # https://travis-ci.community/t/missing-api-key-when-deploying-to-github-releases/5761/14
  # https://docs.travis-ci.com/user/deployment-v2/providers/npm/
  - provider: npm
    edge: true
    email: $NPM_EMAIL
    # api_key: $NPM_API_TOKEN
    on:
      tags: true
